/*
 * 前置收银台
 * 前置收银台
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.scenario.bindcard.domain.model.frontcashier;

import com.yeepay.yop.scenario.bindcard.domain.model.frontcashier.request.*;
import com.yeepay.yop.scenario.bindcard.domain.model.frontcashier.response.*;
import com.yeepay.yop.scenario.bindcard.domain.model.frontcashier.request.*;
import com.yeepay.yop.scenario.bindcard.domain.model.frontcashier.response.*;
import com.yeepay.yop.sdk.exception.YopClientException;

public interface FrontcashierClient {
    /**
     * 【NOP】鉴权绑卡查询绑卡列表
     * 【NOP】鉴权绑卡查询绑卡列表
     *
     * @return BindcardBindcardlistResponse
     * @throws YopClientException if fails to make API call
     */
    BindcardBindcardlistResponse bindcardBindcardlist(BindcardBindcardlistRequest request) throws YopClientException;

    /**
     * 中台绑卡-短验确认
     * &lt;p&gt;该接口提供鉴权绑卡请求短信验证&lt;/p&gt;
     *
     * @return BindcardConfirmV2Response
     * @throws YopClientException if fails to make API call
     */
    BindcardConfirmV2Response bindcardConfirmV2(BindcardConfirmV2Request request) throws YopClientException;

    /**
     * 中台绑卡-绑卡请求
     * &lt;p&gt;该接口提供绑卡请求,该接口请求成功后需调求短验确认接口完成整个绑卡动作&lt;/p&gt;
     *
     * @return BindcardRequestV2Response
     * @throws YopClientException if fails to make API call
     */
    BindcardRequestV2Response bindcardRequestV2(BindcardRequestV2Request request) throws YopClientException;

    /**
     * API收银台绑卡支付确认支付
     * API收银台，绑卡支付，确认支付
     *
     * @return BindpayConfirmResponse
     * @throws YopClientException if fails to make API call
     */
    BindpayConfirmResponse bindpayConfirm(BindpayConfirmRequest request) throws YopClientException;

    /**
     * API收银台绑卡支付请求下单
     *
     * @return BindpayRequestResponse
     * @throws YopClientException if fails to make API call
     */
    BindpayRequestResponse bindpayRequest(BindpayRequestRequest request) throws YopClientException;

    /**
     * API收银台绑卡支付请求发送验证码
     * API收银台，绑卡支付，请求发送验证码
     *
     * @return BindpaySendsmsResponse
     * @throws YopClientException if fails to make API call
     */
    BindpaySendsmsResponse bindpaySendsms(BindpaySendsmsRequest request) throws YopClientException;


    /**
     * Shuts down this client object, releasing any resources that might be held open. This is an optional method, and
     * callers are not expected to call it, but can if they want to explicitly release any open resources. Once a client
     * has been shutdown, it should not be used to make any more requests.
     */
    void shutdown();
}
