/*
 * 前置收银台
 * 前置收银台
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.scenario.bindcard.domain.model.frontcashier;


import com.yeepay.yop.sdk.auth.req.AuthorizationReqRegistry;
import com.yeepay.yop.sdk.auth.req.DefaultAuthorizationReqRegistry;
import com.yeepay.yop.sdk.client.AbstractServiceClientBuilder;
import com.yeepay.yop.sdk.client.ClientParams;

public class FrontcashierClientBuilder extends AbstractServiceClientBuilder<FrontcashierClientBuilder, FrontcashierClientImpl> {

    private static final AuthorizationReqRegistry REGISTRY;

    static {
        REGISTRY = new DefaultAuthorizationReqRegistry();
        REGISTRY.register("bindcardBindcardlist", "YOP-SM2-SM3,YOP-RSA2048-SHA256");
        REGISTRY.register("bindcardConfirmV2", "YOP-SM2-SM3,YOP-RSA2048-SHA256");
        REGISTRY.register("bindcardRequestV2", "YOP-SM2-SM3,YOP-RSA2048-SHA256");
        REGISTRY.register("bindpayConfirm", "YOP-SM2-SM3,YOP-RSA2048-SHA256");
        REGISTRY.register("bindpayRequest", "YOP-SM2-SM3,YOP-RSA2048-SHA256");
        REGISTRY.register("bindpaySendsms", "YOP-SM2-SM3,YOP-RSA2048-SHA256");
    }

    /**
     * @return Create new instance of builder with all defaults set.
     */
    public static FrontcashierClientBuilder builder() {
        return new FrontcashierClientBuilder();
    }

    @Override
    protected AuthorizationReqRegistry authorizationReqRegistry() {
        return REGISTRY;
    }

    @Override
    protected FrontcashierClientImpl build(ClientParams params) {
        return new FrontcashierClientImpl(params);
    }

}
