/*
 * 前置收银台
 * 前置收银台
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.scenario.bindcard.domain.model.frontcashier.request;

import com.yeepay.yop.sdk.http.Headers;
import com.yeepay.yop.sdk.http.HttpMethodName;
import com.yeepay.yop.sdk.http.YopContentType;
import com.yeepay.yop.sdk.internal.DefaultRequest;
import com.yeepay.yop.sdk.internal.Request;
import com.yeepay.yop.sdk.model.transform.RequestMarshaller;
import com.yeepay.yop.sdk.protocol.marshaller.PrimitiveMarshallerUtils;

import java.util.Map;
import java.util.UUID;


public class BindpayRequestRequestMarshaller implements RequestMarshaller<BindpayRequestRequest> {
    private final String serviceName = "Frontcashier";

    private final String resourcePath = "/rest/v1.0/frontcashier/bindpay/request";

    private final String contentType = "application/x-www-form-urlencoded";

    private final HttpMethodName httpMethodName = HttpMethodName.POST;

    public static BindpayRequestRequestMarshaller getInstance() {
        return CacheInstanceHolder.INSTANCE;
    }

    @Override
    public Request<BindpayRequestRequest> marshall(BindpayRequestRequest request) {
        Request<BindpayRequestRequest> internalRequest = new DefaultRequest<BindpayRequestRequest>(request, serviceName);
        internalRequest.setResourcePath(resourcePath);
        internalRequest.setHttpMethod(httpMethodName);
        if (!internalRequest.getHeaders().containsKey(Headers.YOP_REQUEST_ID)) {
            String requestId = UUID.randomUUID().toString();
            internalRequest.addHeader(Headers.YOP_REQUEST_ID, requestId);
        }
        Map<String, String> customerHeaders = request.getHeaders();
        if (customerHeaders != null) {
            for (String key : customerHeaders.keySet()) {
                internalRequest.addHeader(key, customerHeaders.get(key));
            }
        }
        if (request.getToken() != null) {
            internalRequest.addParameter("token", PrimitiveMarshallerUtils.marshalling(request.getToken(), "String"));
        }
        if (request.getBindId() != null) {
            internalRequest.addParameter("bindId", PrimitiveMarshallerUtils.marshalling(request.getBindId(), "String"));
        }
        if (request.getUserNo() != null) {
            internalRequest.addParameter("userNo", PrimitiveMarshallerUtils.marshalling(request.getUserNo(), "String"));
        }
        if (request.getUserType() != null) {
            internalRequest.addParameter("userType", PrimitiveMarshallerUtils.marshalling(request.getUserType(), "String"));
        }
        if (request.getUserIp() != null) {
            internalRequest.addParameter("userIp", PrimitiveMarshallerUtils.marshalling(request.getUserIp(), "String"));
        }
        if (request.getVersion() != null) {
            internalRequest.addParameter("version", PrimitiveMarshallerUtils.marshalling(request.getVersion(), "String"));
        }
        if (request.getPayMerchantNo() != null) {
            internalRequest.addParameter("payMerchantNo", PrimitiveMarshallerUtils.marshalling(request.getPayMerchantNo(), "String"));
        }
        if (request.getExtParamMap() != null) {
            internalRequest.addParameter("extParamMap", PrimitiveMarshallerUtils.marshalling(request.getExtParamMap(), "String"));
        }
        if (request.getDeviceInfo() != null) {
            internalRequest.addParameter("deviceInfo", PrimitiveMarshallerUtils.marshalling(request.getDeviceInfo(), "String"));
        }
        internalRequest.setContentType(YopContentType.FORM_URL_ENCODE);
        internalRequest.addHeader(Headers.CONTENT_TYPE, internalRequest.getContentType().getValue());
        return internalRequest;
    }

    private static class CacheInstanceHolder {
        public static BindpayRequestRequestMarshaller INSTANCE = new BindpayRequestRequestMarshaller();

        private CacheInstanceHolder() {
        }
    }
}
