/*
 * 标准交易
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.scenario.bindcard.client.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.commons.lang3.ObjectUtils;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 未命名
 */
public class YopSubOrderDetailDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 商户编号&lt;br&gt;&lt;span style&#x3D;\&quot;caret-color: #333333; color: #333333; font-family: Arial, sans-serif;\&quot;&gt;商户编号&lt;/span&gt;
     */
    @JsonProperty("merchantNo")
    private String merchantNo = null;

    /**
     * 商户收款请求号&lt;br&gt;&lt;span style&#x3D;\&quot;caret-color: #333333; color: #333333; font-family: Arial, sans-serif;\&quot;&gt;商户收款请求号&lt;/span&gt;
     */
    @JsonProperty("orderId")
    private String orderId = null;

    /**
     * 易宝收款订单号&lt;br&gt;&lt;span style&#x3D;\&quot;caret-color: #333333; color: #333333; font-family: Arial, sans-serif;\&quot;&gt;易宝收款订单号&lt;/span&gt;
     */
    @JsonProperty("uniqueOrderNo")
    private String uniqueOrderNo = null;

    /**
     * 订单金额&lt;br&gt;&lt;span style&#x3D;\&quot;caret-color: #333333; color: #333333; font-family: Arial, sans-serif;\&quot;&gt;订单金额&lt;/span&gt;
     */
    @JsonProperty("orderAmount")
    private BigDecimal orderAmount = null;

    public YopSubOrderDetailDTO merchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
        return this;
    }

    /**
     * 商户编号&lt;br&gt;&lt;span style&#x3D;\&quot;caret-color: #333333; color: #333333; font-family: Arial, sans-serif;\&quot;&gt;商户编号&lt;/span&gt;
     *
     * @return merchantNo
     **/

    public String getMerchantNo() {
        return merchantNo;
    }

    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
    }

    public YopSubOrderDetailDTO orderId(String orderId) {
        this.orderId = orderId;
        return this;
    }

    /**
     * 商户收款请求号&lt;br&gt;&lt;span style&#x3D;\&quot;caret-color: #333333; color: #333333; font-family: Arial, sans-serif;\&quot;&gt;商户收款请求号&lt;/span&gt;
     *
     * @return orderId
     **/

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public YopSubOrderDetailDTO uniqueOrderNo(String uniqueOrderNo) {
        this.uniqueOrderNo = uniqueOrderNo;
        return this;
    }

    /**
     * 易宝收款订单号&lt;br&gt;&lt;span style&#x3D;\&quot;caret-color: #333333; color: #333333; font-family: Arial, sans-serif;\&quot;&gt;易宝收款订单号&lt;/span&gt;
     *
     * @return uniqueOrderNo
     **/

    public String getUniqueOrderNo() {
        return uniqueOrderNo;
    }

    public void setUniqueOrderNo(String uniqueOrderNo) {
        this.uniqueOrderNo = uniqueOrderNo;
    }

    public YopSubOrderDetailDTO orderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
        return this;
    }

    /**
     * 订单金额&lt;br&gt;&lt;span style&#x3D;\&quot;caret-color: #333333; color: #333333; font-family: Arial, sans-serif;\&quot;&gt;订单金额&lt;/span&gt;
     *
     * @return orderAmount
     **/

    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        YopSubOrderDetailDTO yopSubOrderDetailDTO = (YopSubOrderDetailDTO) o;
        return ObjectUtils.equals(this.merchantNo, yopSubOrderDetailDTO.merchantNo) &&
                ObjectUtils.equals(this.orderId, yopSubOrderDetailDTO.orderId) &&
                ObjectUtils.equals(this.uniqueOrderNo, yopSubOrderDetailDTO.uniqueOrderNo) &&
                ObjectUtils.equals(this.orderAmount, yopSubOrderDetailDTO.orderAmount);
    }

    @Override
    public int hashCode() {
        return ObjectUtils.hashCodeMulti(merchantNo, orderId, uniqueOrderNo, orderAmount);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class YopSubOrderDetailDTO {\n");

        sb.append("    merchantNo: ").append(toIndentedString(merchantNo)).append("\n");
        sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
        sb.append("    uniqueOrderNo: ").append(toIndentedString(uniqueOrderNo)).append("\n");
        sb.append("    orderAmount: ").append(toIndentedString(orderAmount)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

