spring:
  application:
    name: yop-java-demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_empty
    locale: zh_CN
    time-zone: GMT+8
  datasource:
    dynamic:
      primary: h2
      datasource:
        h2:
          driver-class-name: org.h2.Driver
          url: jdbc:h2:mem:test;MODE=MySQL
          username: root
          password: test
          init:
            schema: classpath:db/schema-mysql.sql
            data: classpath:db/data-mysql.sql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      continue-on-error: false
server:
  port: 8080
