/*
 * 前置收银台
 * 前置收银台
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.scenario.bindcard.domain.model.frontcashier.response;


import com.yeepay.yop.scenario.bindcard.domain.model.frontcashier.model.BindpayConfirmApiBindPayConfirmResponseDTOResult;

public class BindpayConfirmResponse extends com.yeepay.yop.sdk.model.BaseResponse {
    private static final long serialVersionUID = 1L;

    private BindpayConfirmApiBindPayConfirmResponseDTOResult result;

    public BindpayConfirmApiBindPayConfirmResponseDTOResult getResult() {
        return result;
    }

    public void setResult(BindpayConfirmApiBindPayConfirmResponseDTOResult result) {
        this.result = result;
    }

}
