/*
 * 标准交易
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.scenario.bindcard.domain.model.trade.request;


import com.yeepay.yop.sdk.model.BaseRequest;

public class OrderRequest extends BaseRequest {
    private static final long serialVersionUID = 1L;

    private String parentMerchantNo;

    private String merchantNo;

    private String orderId;

    private String orderAmount;

    private String goodsName;

    private String fundProcessType;

    private String notifyUrl;

    private String memo;

    private String subOrderDetail;

    private String expiredTime;

    private String redirectUrl;

    private String csUrl;

    private String businessInfo;

    private String terminalInfo;

    private String ypPromotionInfo;

    private String payerInfo;

    private String payMerchantNo;

    private String productInfo;


    /**
     * Get parentMerchantNo
     *
     * @return parentMerchantNo
     **/

    public String getParentMerchantNo() {
        return parentMerchantNo;
    }

    public void setParentMerchantNo(String parentMerchantNo) {
        this.parentMerchantNo = parentMerchantNo;
    }

    /**
     * Get merchantNo
     *
     * @return merchantNo
     **/

    public String getMerchantNo() {
        return merchantNo;
    }

    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
    }

    /**
     * Get orderId
     *
     * @return orderId
     **/

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * Get orderAmount
     *
     * @return orderAmount
     **/

    public String getOrderAmount() {
        return orderAmount;
    }

    public void setOrderAmount(String orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * Get goodsName
     *
     * @return goodsName
     **/

    public String getGoodsName() {
        return goodsName;
    }

    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /**
     * Get fundProcessType
     *
     * @return fundProcessType
     **/

    public String getFundProcessType() {
        return fundProcessType;
    }

    public void setFundProcessType(String fundProcessType) {
        this.fundProcessType = fundProcessType;
    }

    /**
     * Get notifyUrl
     *
     * @return notifyUrl
     **/

    public String getNotifyUrl() {
        return notifyUrl;
    }

    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
    }

    /**
     * Get memo
     *
     * @return memo
     **/

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * Get subOrderDetail
     *
     * @return subOrderDetail
     **/

    public String getSubOrderDetail() {
        return subOrderDetail;
    }

    public void setSubOrderDetail(String subOrderDetail) {
        this.subOrderDetail = subOrderDetail;
    }

    /**
     * Get expiredTime
     *
     * @return expiredTime
     **/

    public String getExpiredTime() {
        return expiredTime;
    }

    public void setExpiredTime(String expiredTime) {
        this.expiredTime = expiredTime;
    }

    /**
     * Get redirectUrl
     *
     * @return redirectUrl
     **/

    public String getRedirectUrl() {
        return redirectUrl;
    }

    public void setRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl;
    }

    /**
     * Get csUrl
     *
     * @return csUrl
     **/

    public String getCsUrl() {
        return csUrl;
    }

    public void setCsUrl(String csUrl) {
        this.csUrl = csUrl;
    }

    /**
     * Get businessInfo
     *
     * @return businessInfo
     **/

    public String getBusinessInfo() {
        return businessInfo;
    }

    public void setBusinessInfo(String businessInfo) {
        this.businessInfo = businessInfo;
    }

    /**
     * Get terminalInfo
     *
     * @return terminalInfo
     **/

    public String getTerminalInfo() {
        return terminalInfo;
    }

    public void setTerminalInfo(String terminalInfo) {
        this.terminalInfo = terminalInfo;
    }

    /**
     * Get ypPromotionInfo
     *
     * @return ypPromotionInfo
     **/

    public String getYpPromotionInfo() {
        return ypPromotionInfo;
    }

    public void setYpPromotionInfo(String ypPromotionInfo) {
        this.ypPromotionInfo = ypPromotionInfo;
    }

    /**
     * Get payerInfo
     *
     * @return payerInfo
     **/

    public String getPayerInfo() {
        return payerInfo;
    }

    public void setPayerInfo(String payerInfo) {
        this.payerInfo = payerInfo;
    }

    /**
     * Get payMerchantNo
     *
     * @return payMerchantNo
     **/

    public String getPayMerchantNo() {
        return payMerchantNo;
    }

    public void setPayMerchantNo(String payMerchantNo) {
        this.payMerchantNo = payMerchantNo;
    }

    /**
     * Get productInfo
     *
     * @return productInfo
     **/

    public String getProductInfo() {
        return productInfo;
    }

    public void setProductInfo(String productInfo) {
        this.productInfo = productInfo;
    }

    @Override
    public String getOperationId() {
        return "order";
    }
}
