/*
 * 标准交易
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.scenario.bindcard.domain.model.trade;


import com.yeepay.yop.scenario.bindcard.domain.model.trade.request.OrderQueryRequest;
import com.yeepay.yop.scenario.bindcard.domain.model.trade.request.OrderRequest;
import com.yeepay.yop.scenario.bindcard.domain.model.trade.response.OrderQueryResponse;
import com.yeepay.yop.scenario.bindcard.domain.model.trade.response.OrderResponse;
import com.yeepay.yop.sdk.exception.YopClientException;

public interface TradeClient {

    /**
     * 交易下单
     * 交易下单
     *
     * @return OrderResponse
     * @throws YopClientException if fails to make API call
     */
    OrderResponse order(OrderRequest request) throws YopClientException;

    /**
     * 查询订单
     * 查询订单
     *
     * @return OrderQueryResponse
     * @throws YopClientException if fails to make API call
     */
    OrderQueryResponse orderQuery(OrderQueryRequest request) throws YopClientException;


    /**
     * Shuts down this client object, releasing any resources that might be held open. This is an optional method, and
     * callers are not expected to call it, but can if they want to explicitly release any open resources. Once a client
     * has been shutdown, it should not be used to make any more requests.
     */
    void shutdown();
}
