/*
 * 标准交易
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.scenario.bindcard.domain.model.trade;


import com.yeepay.yop.sdk.auth.req.AuthorizationReqRegistry;
import com.yeepay.yop.sdk.auth.req.DefaultAuthorizationReqRegistry;
import com.yeepay.yop.sdk.client.AbstractServiceClientBuilder;
import com.yeepay.yop.sdk.client.ClientParams;

public class TradeClientBuilder extends AbstractServiceClientBuilder<TradeClientBuilder, TradeClientImpl> {

    private static final AuthorizationReqRegistry REGISTRY;

    static {
        REGISTRY = new DefaultAuthorizationReqRegistry();
        REGISTRY.register("order", "YOP-SM2-SM3,YOP-RSA2048-SHA256");
        REGISTRY.register("orderQuery", "YOP-SM2-SM3,YOP-RSA2048-SHA256");
    }

    /**
     * @return Create new instance of builder with all defaults set.
     */
    public static TradeClientBuilder builder() {
        return new TradeClientBuilder();
    }

    @Override
    protected AuthorizationReqRegistry authorizationReqRegistry() {
        return REGISTRY;
    }

    @Override
    protected TradeClientImpl build(ClientParams params) {
        return new TradeClientImpl(params);
    }

}
