/*
 * 标准交易
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.yeepay.yop.scenario.bindcard.domain.model.trade.response;


import com.yeepay.yop.scenario.bindcard.domain.model.trade.model.YopQueryOrderRes;
import com.yeepay.yop.sdk.model.BaseResponse;

public class OrderQueryResponse extends BaseResponse {
    private static final long serialVersionUID = 1L;

    private YopQueryOrderRes result;

    public YopQueryOrderRes getResult() {
        return result;
    }

    public void setResult(YopQueryOrderRes result) {
        this.result = result;
    }

}
