/*
 * 前置收银台
 * 前置收银台
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.scenario.bindcard.domain.model.frontcashier.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.commons.lang3.ObjectUtils;

import java.io.Serializable;

/**
 * BindcardRequestV2OpenAuthBindCardResponseDTOResult
 */
public class BindcardRequestV2OpenAuthBindCardResponseDTOResult implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 返回码
     */
    @JsonProperty("code")
    private String code = null;

    /**
     * 返回信息
     */
    @JsonProperty("message")
    private String message = null;

    /**
     * 主商户编号
     */
    @JsonProperty("parentMerchantNo")
    private String parentMerchantNo = null;

    /**
     * 商户编号
     */
    @JsonProperty("merchantNo")
    private String merchantNo = null;

    /**
     * 绑卡请求号
     */
    @JsonProperty("merchantFlowId")
    private String merchantFlowId = null;

    /**
     * 易宝绑卡流水号
     */
    @JsonProperty("nopOrderId")
    private String nopOrderId = null;

    /**
     * 绑卡ID
     */
    @JsonProperty("bindId")
    private String bindId = null;

    /**
     * 签约状态
     */
    @JsonProperty("signStatus")
    private String signStatus = null;

    public BindcardRequestV2OpenAuthBindCardResponseDTOResult code(String code) {
        this.code = code;
        return this;
    }

    /**
     * 返回码
     *
     * @return code
     **/

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public BindcardRequestV2OpenAuthBindCardResponseDTOResult message(String message) {
        this.message = message;
        return this;
    }

    /**
     * 返回信息
     *
     * @return message
     **/

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public BindcardRequestV2OpenAuthBindCardResponseDTOResult parentMerchantNo(String parentMerchantNo) {
        this.parentMerchantNo = parentMerchantNo;
        return this;
    }

    /**
     * 主商户编号
     *
     * @return parentMerchantNo
     **/

    public String getParentMerchantNo() {
        return parentMerchantNo;
    }

    public void setParentMerchantNo(String parentMerchantNo) {
        this.parentMerchantNo = parentMerchantNo;
    }

    public BindcardRequestV2OpenAuthBindCardResponseDTOResult merchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
        return this;
    }

    /**
     * 商户编号
     *
     * @return merchantNo
     **/

    public String getMerchantNo() {
        return merchantNo;
    }

    public void setMerchantNo(String merchantNo) {
        this.merchantNo = merchantNo;
    }

    public BindcardRequestV2OpenAuthBindCardResponseDTOResult merchantFlowId(String merchantFlowId) {
        this.merchantFlowId = merchantFlowId;
        return this;
    }

    /**
     * 绑卡请求号
     *
     * @return merchantFlowId
     **/

    public String getMerchantFlowId() {
        return merchantFlowId;
    }

    public void setMerchantFlowId(String merchantFlowId) {
        this.merchantFlowId = merchantFlowId;
    }

    public BindcardRequestV2OpenAuthBindCardResponseDTOResult nopOrderId(String nopOrderId) {
        this.nopOrderId = nopOrderId;
        return this;
    }

    /**
     * 易宝绑卡流水号
     *
     * @return nopOrderId
     **/

    public String getNopOrderId() {
        return nopOrderId;
    }

    public void setNopOrderId(String nopOrderId) {
        this.nopOrderId = nopOrderId;
    }

    public BindcardRequestV2OpenAuthBindCardResponseDTOResult bindId(String bindId) {
        this.bindId = bindId;
        return this;
    }

    /**
     * 绑卡ID
     *
     * @return bindId
     **/

    public String getBindId() {
        return bindId;
    }

    public void setBindId(String bindId) {
        this.bindId = bindId;
    }

    public BindcardRequestV2OpenAuthBindCardResponseDTOResult signStatus(String signStatus) {
        this.signStatus = signStatus;
        return this;
    }

    /**
     * 签约状态
     *
     * @return signStatus
     **/

    public String getSignStatus() {
        return signStatus;
    }

    public void setSignStatus(String signStatus) {
        this.signStatus = signStatus;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BindcardRequestV2OpenAuthBindCardResponseDTOResult bindcardRequestV2OpenAuthBindCardResponseDTOResult = (BindcardRequestV2OpenAuthBindCardResponseDTOResult) o;
        return ObjectUtils.equals(this.code, bindcardRequestV2OpenAuthBindCardResponseDTOResult.code) &&
                ObjectUtils.equals(this.message, bindcardRequestV2OpenAuthBindCardResponseDTOResult.message) &&
                ObjectUtils.equals(this.parentMerchantNo, bindcardRequestV2OpenAuthBindCardResponseDTOResult.parentMerchantNo) &&
                ObjectUtils.equals(this.merchantNo, bindcardRequestV2OpenAuthBindCardResponseDTOResult.merchantNo) &&
                ObjectUtils.equals(this.merchantFlowId, bindcardRequestV2OpenAuthBindCardResponseDTOResult.merchantFlowId) &&
                ObjectUtils.equals(this.nopOrderId, bindcardRequestV2OpenAuthBindCardResponseDTOResult.nopOrderId) &&
                ObjectUtils.equals(this.bindId, bindcardRequestV2OpenAuthBindCardResponseDTOResult.bindId) &&
                ObjectUtils.equals(this.signStatus, bindcardRequestV2OpenAuthBindCardResponseDTOResult.signStatus);
    }

    @Override
    public int hashCode() {
        return ObjectUtils.hashCodeMulti(code, message, parentMerchantNo, merchantNo, merchantFlowId, nopOrderId, bindId, signStatus);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class BindcardRequestV2OpenAuthBindCardResponseDTOResult {\n");

        sb.append("    code: ").append(toIndentedString(code)).append("\n");
        sb.append("    message: ").append(toIndentedString(message)).append("\n");
        sb.append("    parentMerchantNo: ").append(toIndentedString(parentMerchantNo)).append("\n");
        sb.append("    merchantNo: ").append(toIndentedString(merchantNo)).append("\n");
        sb.append("    merchantFlowId: ").append(toIndentedString(merchantFlowId)).append("\n");
        sb.append("    nopOrderId: ").append(toIndentedString(nopOrderId)).append("\n");
        sb.append("    bindId: ").append(toIndentedString(bindId)).append("\n");
        sb.append("    signStatus: ").append(toIndentedString(signStatus)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

