/*
 * 标准交易
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.scenario.bindcard.domain.model.trade.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.commons.lang3.ObjectUtils;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 未命名
 */
public class ChannelPromotionInfo implements Serializable {

  private static final long serialVersionUID = 1L;

  /**
   * 优惠券编码
   */
  @JsonProperty("promotionId")
  private String promotionId = null;

  /**
   * 优惠券名称
   */
  @JsonProperty("promotionName")
  private String promotionName = null;

  /**
   * 优惠券范围(全场、单品)
   */
  @JsonProperty("promotionScope")
  private String promotionScope = null;

  /**
   * 优惠券金额
   */
  @JsonProperty("amount")
  private BigDecimal amount = null;

  /**
   * 优惠券活动id
   */
  @JsonProperty("activityId")
  private String activityId = null;

  /**
   * 渠道出资
   */
  @JsonProperty("channelContribute")
  private String channelContribute = null;

  /**
   * 商户出资
   */
  @JsonProperty("merchantContribute")
  private String merchantContribute = null;

  /**
   * 其他出资
   */
  @JsonProperty("otherContribute")
  private String otherContribute = null;

  /**
   * 备注信息
   */
  @JsonProperty("memo")
  private String memo = null;

  public ChannelPromotionInfo promotionId(String promotionId) {
    this.promotionId = promotionId;
    return this;
  }

  /**
   * 优惠券编码
   *
   * @return promotionId
   **/

  public String getPromotionId() {
    return promotionId;
  }

  public void setPromotionId(String promotionId) {
    this.promotionId = promotionId;
  }

  public ChannelPromotionInfo promotionName(String promotionName) {
    this.promotionName = promotionName;
    return this;
  }

  /**
   * 优惠券名称
   *
   * @return promotionName
   **/

  public String getPromotionName() {
    return promotionName;
  }

  public void setPromotionName(String promotionName) {
    this.promotionName = promotionName;
  }

  public ChannelPromotionInfo promotionScope(String promotionScope) {
    this.promotionScope = promotionScope;
    return this;
  }

  /**
   * 优惠券范围(全场、单品)
   *
   * @return promotionScope
   **/

  public String getPromotionScope() {
    return promotionScope;
  }

  public void setPromotionScope(String promotionScope) {
    this.promotionScope = promotionScope;
  }

  public ChannelPromotionInfo amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

  /**
   * 优惠券金额
   *
   * @return amount
   **/

  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public ChannelPromotionInfo activityId(String activityId) {
    this.activityId = activityId;
    return this;
  }

  /**
   * 优惠券活动id
   *
   * @return activityId
   **/

  public String getActivityId() {
    return activityId;
  }

  public void setActivityId(String activityId) {
    this.activityId = activityId;
  }

  public ChannelPromotionInfo channelContribute(String channelContribute) {
    this.channelContribute = channelContribute;
    return this;
  }

  /**
   * 渠道出资
   *
   * @return channelContribute
   **/

  public String getChannelContribute() {
    return channelContribute;
  }

  public void setChannelContribute(String channelContribute) {
    this.channelContribute = channelContribute;
  }

  public ChannelPromotionInfo merchantContribute(String merchantContribute) {
    this.merchantContribute = merchantContribute;
    return this;
  }

  /**
   * 商户出资
   *
   * @return merchantContribute
   **/

  public String getMerchantContribute() {
    return merchantContribute;
  }

  public void setMerchantContribute(String merchantContribute) {
    this.merchantContribute = merchantContribute;
  }

  public ChannelPromotionInfo otherContribute(String otherContribute) {
    this.otherContribute = otherContribute;
    return this;
  }

  /**
   * 其他出资
   *
   * @return otherContribute
   **/

  public String getOtherContribute() {
    return otherContribute;
  }

  public void setOtherContribute(String otherContribute) {
    this.otherContribute = otherContribute;
  }

  public ChannelPromotionInfo memo(String memo) {
    this.memo = memo;
    return this;
  }

  /**
   * 备注信息
   *
   * @return memo
   **/

  public String getMemo() {
    return memo;
  }

  public void setMemo(String memo) {
    this.memo = memo;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelPromotionInfo channelPromotionInfo = (ChannelPromotionInfo) o;
    return ObjectUtils.equals(this.promotionId, channelPromotionInfo.promotionId) &&
            ObjectUtils.equals(this.promotionName, channelPromotionInfo.promotionName) &&
            ObjectUtils.equals(this.promotionScope, channelPromotionInfo.promotionScope) &&
            ObjectUtils.equals(this.amount, channelPromotionInfo.amount) &&
            ObjectUtils.equals(this.activityId, channelPromotionInfo.activityId) &&
            ObjectUtils.equals(this.channelContribute, channelPromotionInfo.channelContribute) &&
            ObjectUtils.equals(this.merchantContribute, channelPromotionInfo.merchantContribute) &&
            ObjectUtils.equals(this.otherContribute, channelPromotionInfo.otherContribute) &&
            ObjectUtils.equals(this.memo, channelPromotionInfo.memo);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(promotionId, promotionName, promotionScope, amount, activityId, channelContribute, merchantContribute, otherContribute, memo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelPromotionInfoDTO {\n");

    sb.append("    promotionId: ").append(toIndentedString(promotionId)).append("\n");
    sb.append("    promotionName: ").append(toIndentedString(promotionName)).append("\n");
    sb.append("    promotionScope: ").append(toIndentedString(promotionScope)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    activityId: ").append(toIndentedString(activityId)).append("\n");
    sb.append("    channelContribute: ").append(toIndentedString(channelContribute)).append("\n");
    sb.append("    merchantContribute: ").append(toIndentedString(merchantContribute)).append("\n");
    sb.append("    otherContribute: ").append(toIndentedString(otherContribute)).append("\n");
    sb.append("    memo: ").append(toIndentedString(memo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

