/*
 * 标准交易
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.scenario.bindcard.domain.model.trade.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.commons.lang3.ObjectUtils;

import java.io.Serializable;

/**
 * 付款信息&lt;br&gt;&lt;span style&#x3D;\&quot;caret-color: #333333; color: #333333; font-family: Arial, sans-serif;\&quot;&gt;付款信息&lt;/span&gt;
 */
public class PayerInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 银行编号&lt;br&gt;&lt;span style&#x3D;\&quot;caret-color: #333333; color: #333333; font-family: Arial, sans-serif;\&quot;&gt;银行编号，&lt;/span&gt;&lt;span style&#x3D;\&quot;caret-color: #333333; color: #333333; font-family: Arial, sans-serif;\&quot;&gt;如：ABC、CBC等&lt;/span&gt;
     */
    @JsonProperty("bankId")
    private String bankId = null;

    /**
     * 账户名称.网银B2B支付会返回付款企业账户名称
     */
    @JsonProperty("accountName")
    private String accountName = null;

    /**
     * 银行卡号（前6后4）
     */
    @JsonProperty("bankCardNo")
    private String bankCardNo = null;

    /**
     * 手机号（前3后4)
     */
    @JsonProperty("mobilePhoneNo")
    private String mobilePhoneNo = null;

    /**
     * 卡类型&lt;br&gt;DEBIT：借记卡CREDIT：贷记卡CFT：微信零钱QUASI_CREDIT：准贷记卡PUBLIC_ACCOUNT：对公账户（网银B2B支付返回）
     */
    @JsonProperty("cardType")
    private String cardType = null;

    /**
     * 用户ID&lt;br&gt;微信支付返回openID&lt;br&gt;支付宝支付返回userID&lt;br&gt;银联支付返回userID&lt;br&gt;账户支付返回付款方商编
     */
    @JsonProperty("userID")
    private String userID = null;

    /**
     * unionID&lt;br&gt;&lt;span style&#x3D;\&quot;caret-color: #333333; color: #333333; font-family: Arial, sans-serif;\&quot;&gt;微信返回的unionID&lt;/span&gt;
     */
    @JsonProperty("unionID")
    private String unionID = null;

    /**
     * 支付宝买家登录账号&lt;br&gt;支付宝支付返回buyerLogonId
     */
    @JsonProperty("buyerLogonId")
    private String buyerLogonId = null;

    /**
     * 记帐簿编号
     */
    @JsonProperty("ypAccountBookNo")
    private String ypAccountBookNo = null;

    public PayerInfo bankId(String bankId) {
        this.bankId = bankId;
        return this;
    }

    /**
     * 银行编号&lt;br&gt;&lt;span style&#x3D;\&quot;caret-color: #333333; color: #333333; font-family: Arial, sans-serif;\&quot;&gt;银行编号，&lt;/span&gt;&lt;span style&#x3D;\&quot;caret-color: #333333; color: #333333; font-family: Arial, sans-serif;\&quot;&gt;如：ABC、CBC等&lt;/span&gt;
     *
     * @return bankId
     **/

    public String getBankId() {
        return bankId;
    }

    public void setBankId(String bankId) {
        this.bankId = bankId;
    }

    public PayerInfo accountName(String accountName) {
        this.accountName = accountName;
        return this;
    }

    /**
     * 账户名称.网银B2B支付会返回付款企业账户名称
     *
     * @return accountName
     **/

    public String getAccountName() {
        return accountName;
    }

    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    public PayerInfo bankCardNo(String bankCardNo) {
        this.bankCardNo = bankCardNo;
        return this;
    }

    /**
     * 银行卡号（前6后4）
     *
     * @return bankCardNo
     **/

    public String getBankCardNo() {
        return bankCardNo;
    }

    public void setBankCardNo(String bankCardNo) {
        this.bankCardNo = bankCardNo;
    }

    public PayerInfo mobilePhoneNo(String mobilePhoneNo) {
        this.mobilePhoneNo = mobilePhoneNo;
        return this;
    }

    /**
     * 手机号（前3后4)
     *
     * @return mobilePhoneNo
     **/

    public String getMobilePhoneNo() {
        return mobilePhoneNo;
    }

    public void setMobilePhoneNo(String mobilePhoneNo) {
        this.mobilePhoneNo = mobilePhoneNo;
    }

    public PayerInfo cardType(String cardType) {
        this.cardType = cardType;
        return this;
    }

    /**
     * 卡类型&lt;br&gt;DEBIT：借记卡CREDIT：贷记卡CFT：微信零钱QUASI_CREDIT：准贷记卡PUBLIC_ACCOUNT：对公账户（网银B2B支付返回）
     *
     * @return cardType
     **/

    public String getCardType() {
        return cardType;
    }

    public void setCardType(String cardType) {
        this.cardType = cardType;
    }

    public PayerInfo userID(String userID) {
        this.userID = userID;
        return this;
    }

    /**
     * 用户ID&lt;br&gt;微信支付返回openID&lt;br&gt;支付宝支付返回userID&lt;br&gt;银联支付返回userID&lt;br&gt;账户支付返回付款方商编
     *
     * @return userID
     **/

    public String getUserID() {
        return userID;
    }

    public void setUserID(String userID) {
        this.userID = userID;
    }

    public PayerInfo unionID(String unionID) {
        this.unionID = unionID;
        return this;
    }

    /**
     * unionID&lt;br&gt;&lt;span style&#x3D;\&quot;caret-color: #333333; color: #333333; font-family: Arial, sans-serif;\&quot;&gt;微信返回的unionID&lt;/span&gt;
     *
     * @return unionID
     **/

    public String getUnionID() {
        return unionID;
    }

    public void setUnionID(String unionID) {
        this.unionID = unionID;
    }

    public PayerInfo buyerLogonId(String buyerLogonId) {
        this.buyerLogonId = buyerLogonId;
        return this;
    }

    /**
     * 支付宝买家登录账号&lt;br&gt;支付宝支付返回buyerLogonId
     *
     * @return buyerLogonId
     **/

    public String getBuyerLogonId() {
        return buyerLogonId;
    }

    public void setBuyerLogonId(String buyerLogonId) {
        this.buyerLogonId = buyerLogonId;
    }

    public PayerInfo ypAccountBookNo(String ypAccountBookNo) {
        this.ypAccountBookNo = ypAccountBookNo;
        return this;
    }

    /**
     * 记帐簿编号
     *
     * @return ypAccountBookNo
     **/

    public String getYpAccountBookNo() {
        return ypAccountBookNo;
    }

    public void setYpAccountBookNo(String ypAccountBookNo) {
        this.ypAccountBookNo = ypAccountBookNo;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PayerInfo payerInfo = (PayerInfo) o;
        return ObjectUtils.equals(this.bankId, payerInfo.bankId) &&
                ObjectUtils.equals(this.accountName, payerInfo.accountName) &&
                ObjectUtils.equals(this.bankCardNo, payerInfo.bankCardNo) &&
                ObjectUtils.equals(this.mobilePhoneNo, payerInfo.mobilePhoneNo) &&
                ObjectUtils.equals(this.cardType, payerInfo.cardType) &&
                ObjectUtils.equals(this.userID, payerInfo.userID) &&
                ObjectUtils.equals(this.unionID, payerInfo.unionID) &&
                ObjectUtils.equals(this.buyerLogonId, payerInfo.buyerLogonId) &&
                ObjectUtils.equals(this.ypAccountBookNo, payerInfo.ypAccountBookNo);
    }

    @Override
    public int hashCode() {
        return ObjectUtils.hashCodeMulti(bankId, accountName, bankCardNo, mobilePhoneNo, cardType, userID, unionID, buyerLogonId, ypAccountBookNo);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PayerInfo {\n");

        sb.append("    bankId: ").append(toIndentedString(bankId)).append("\n");
        sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
        sb.append("    bankCardNo: ").append(toIndentedString(bankCardNo)).append("\n");
        sb.append("    mobilePhoneNo: ").append(toIndentedString(mobilePhoneNo)).append("\n");
        sb.append("    cardType: ").append(toIndentedString(cardType)).append("\n");
        sb.append("    userID: ").append(toIndentedString(userID)).append("\n");
        sb.append("    unionID: ").append(toIndentedString(unionID)).append("\n");
        sb.append("    buyerLogonId: ").append(toIndentedString(buyerLogonId)).append("\n");
        sb.append("    ypAccountBookNo: ").append(toIndentedString(ypAccountBookNo)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

