/*
 * 标准交易
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.yeepay.yop.scenario.bindcard.domain.model.trade.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.apache.commons.lang3.ObjectUtils;

import java.io.Serializable;

/**
 * 未命名
 */
public class YpPromotionInfo implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * 营销活动编号
     */
    @JsonProperty("marketNo")
    private String marketNo = null;

    /**
     * 营销订单号
     */
    @JsonProperty("subsidyOrderNo")
    private String subsidyOrderNo = null;

    /**
     * 营销类型&lt;br&gt;CUSTOM_REDUCTION:自定义金额立减CUSTOM_ALLOWANCE:自定义金额补贴
     */
    @JsonProperty("type")
    private String type = null;

    /**
     * 营销金额
     */
    @JsonProperty("amount")
    private String amount = null;

    /**
     * 出资方商编
     */
    @JsonProperty("contributeMerchant")
    private String contributeMerchant = null;

    /**
     * 营销状态
     */
    @JsonProperty("status")
    private String status = null;

    public YpPromotionInfo marketNo(String marketNo) {
        this.marketNo = marketNo;
        return this;
    }

    /**
     * 营销活动编号
     *
     * @return marketNo
     **/

    public String getMarketNo() {
        return marketNo;
    }

    public void setMarketNo(String marketNo) {
        this.marketNo = marketNo;
    }

    public YpPromotionInfo subsidyOrderNo(String subsidyOrderNo) {
        this.subsidyOrderNo = subsidyOrderNo;
        return this;
    }

    /**
     * 营销订单号
     *
     * @return subsidyOrderNo
     **/

    public String getSubsidyOrderNo() {
        return subsidyOrderNo;
    }

    public void setSubsidyOrderNo(String subsidyOrderNo) {
        this.subsidyOrderNo = subsidyOrderNo;
    }

    public YpPromotionInfo type(String type) {
        this.type = type;
        return this;
    }

    /**
     * 营销类型&lt;br&gt;CUSTOM_REDUCTION:自定义金额立减CUSTOM_ALLOWANCE:自定义金额补贴
     *
     * @return type
     **/

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public YpPromotionInfo amount(String amount) {
        this.amount = amount;
        return this;
    }

    /**
     * 营销金额
     *
     * @return amount
     **/

    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public YpPromotionInfo contributeMerchant(String contributeMerchant) {
        this.contributeMerchant = contributeMerchant;
        return this;
    }

    /**
     * 出资方商编
     *
     * @return contributeMerchant
     **/

    public String getContributeMerchant() {
        return contributeMerchant;
    }

    public void setContributeMerchant(String contributeMerchant) {
        this.contributeMerchant = contributeMerchant;
    }

    public YpPromotionInfo status(String status) {
        this.status = status;
        return this;
    }

    /**
     * 营销状态
     *
     * @return status
     **/

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        YpPromotionInfo ypPromotionInfo = (YpPromotionInfo) o;
        return ObjectUtils.equals(this.marketNo, ypPromotionInfo.marketNo) &&
                ObjectUtils.equals(this.subsidyOrderNo, ypPromotionInfo.subsidyOrderNo) &&
                ObjectUtils.equals(this.type, ypPromotionInfo.type) &&
                ObjectUtils.equals(this.amount, ypPromotionInfo.amount) &&
                ObjectUtils.equals(this.contributeMerchant, ypPromotionInfo.contributeMerchant) &&
                ObjectUtils.equals(this.status, ypPromotionInfo.status);
    }

    @Override
    public int hashCode() {
        return ObjectUtils.hashCodeMulti(marketNo, subsidyOrderNo, type, amount, contributeMerchant, status);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class YpPromotionInfoDTO {\n");

        sb.append("    marketNo: ").append(toIndentedString(marketNo)).append("\n");
        sb.append("    subsidyOrderNo: ").append(toIndentedString(subsidyOrderNo)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
        sb.append("    contributeMerchant: ").append(toIndentedString(contributeMerchant)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

